name: torch-rl
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - _ipython_minor_entry_point=8.7.0=h8cf3c4a_0
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.3=py39h02fc5c5_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - aom=3.5.0=h7ea286d_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39h02fc5c5_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - bleach=5.0.1=pyhd8ed1ab_0
  - blinker=1.5=pyhd8ed1ab_0
  - boto3=1.26.35=pyhd8ed1ab_0
  - botocore=1.29.36=pyhd8ed1ab_0
  - brotli=1.0.9=h1a8c8d9_8
  - brotli-bin=1.0.9=h1a8c8d9_8
  - brotlipy=0.7.0=py39h02fc5c5_1005
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2022.12.7=h4653dfc_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.0=pyhd8ed1ab_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39h7e6b969_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - contourpy=1.0.6=py39haaf3ac1_0
  - cryptography=38.0.4=py39he2a39a8_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.4=py39h23fbdae_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hb7217d7_0
  - ffmpeg=5.1.2=gpl_hf318d42_105
  - flask=2.2.2=pyhd8ed1ab_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py39h02fc5c5_1
  - freetype=2.12.1=hd633e50_1
  - frozenlist=1.3.3=py39h02fc5c5_0
  - geos=3.9.1=hc377ac9_1
  - gettext=0.21.1=h0186832_0
  - gmp=6.2.1=h9f76cd9_0
  - gmpy2=2.1.2=py39h0b4f9c6_1
  - gnutls=3.7.8=h9f1a10d_0
  - google-auth=2.16.0=pyh1a96a4e_1
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - grpcio=1.51.1=py39ha768f26_0
  - gym=0.21.0=py39h2804cbe_2
  - h5py=3.7.0=nompi_py39hc9149d8_102
  - hdf5=1.12.2=nompi_ha7af310_101
  - icu=70.1=h6b3803e_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=5.2.0=pyha770c72_0
  - importlib_resources=5.10.1=pyhd8ed1ab_1
  - ipykernel=6.19.4=pyh736e0ef_0
  - ipython=8.7.0=pyhd1c38e8_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.4=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=he4db4b2_2
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter=1.0.0=py39h2804cbe_8
  - jupyter_client=7.4.8=pyhd8ed1ab_0
  - jupyter_console=6.4.4=pyhd8ed1ab_0
  - jupyter_core=5.1.0=py39h2804cbe_0
  - jupyter_events=0.5.0=pyhd8ed1ab_1
  - jupyter_server=2.0.5=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py39haaf3ac1_1
  - krb5=1.20.1=h69eda48_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.14=h481adae_1
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20220623.0=cxx17_h28b99d4_6
  - libaec=1.0.6=hbdafb3b_0
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a8c8d9_8
  - libbrotlidec=1.0.9=h1a8c8d9_8
  - libbrotlienc=1.0.9=h1a8c8d9_8
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=7.87.0=h9049daf_0
  - libcxx=14.0.6=h2692d47_0
  - libdeflate=1.14=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=11_3_0_hd922786_27
  - libgfortran5=11.3.0=hdaf2cc0_27
  - libgrpc=1.51.1=h55edf5b_0
  - libiconv=1.17=he4db4b2_0
  - libidn2=2.3.4=h1a8c8d9_0
  - liblapack=3.9.0=16_osxarm64_openblas
  - libnghttp2=1.47.0=h519802c_1
  - libopenblas=0.3.21=openmp_hc731615_3
  - libpng=1.6.39=h76d750c_0
  - libprotobuf=3.21.12=hb5ab8b9_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.40.0=h76d750c_0
  - libssh2=1.10.0=h7a5bd25_3
  - libtasn1=4.19.0=h1a8c8d9_0
  - libtiff=4.5.0=heb92581_0
  - libunistring=0.9.10=h3422bc3_0
  - libvpx=1.11.0=hc470f4d_3
  - libwebp-base=1.2.4=h57fd34a_0
  - libxcb=1.13=h9b22ae9_1004
  - libxml2=2.10.3=h87b0503_0
  - libxslt=1.1.37=h1bd8bc4_0
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=15.0.6=h7cfbb63_0
  - lxml=4.9.2=py39h0520ce3_0
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39h02fc5c5_2
  - matplotlib=3.6.2=py39hdf13c20_0
  - matplotlib-base=3.6.2=py39h35e9e80_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mpc=1.2.1=h309154c_0
  - mpfr=4.1.0=h6d7a090_1
  - mpmath=1.2.1=pyhd8ed1ab_0
  - multidict=6.0.4=py39h02fc5c5_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.4.8=pyhd8ed1ab_0
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.7=pyhd8ed1ab_0
  - nbconvert-core=7.2.7=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.7=pyhd8ed1ab_0
  - nbformat=5.7.1=pyhd8ed1ab_0
  - ncurses=6.3=h07bb92c_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.8.1=h63371fa_1
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openh264=2.3.1=hb7217d7_1
  - openjpeg=2.5.0=hbc2ba62_2
  - openssl=3.0.7=h03a7124_1
  - p11-kit=0.24.1=h29577a5_0
  - packaging=22.0=pyhd8ed1ab_0
  - pandas=1.5.2=py39hde7b980_0
  - pandas-datareader=0.10.0=pyh6c4a22f_0
  - pandoc=2.19.2=hce30654_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py39h8bd98a6_4
  - pip=22.3.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.6.0=pyhd8ed1ab_0
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - prompt_toolkit=3.0.36=hd8ed1ab_0
  - protobuf=4.21.12=py39h23fbdae_0
  - psutil=5.9.4=py39h02fc5c5_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.19.2=py39h02fc5c5_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.15=hea58f1e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-json-logger=2.0.4=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytorch=2.0.0.dev20221222=py3.9_0
  - pytz=2022.7=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py39h02fc5c5_5
  - pyzmq=24.0.1=py39h0553236_1
  - re2=2022.06.01=h9a09cb3_1
  - readline=8.1.2=h46ed386_0
  - requests=2.28.1=pyhd8ed1ab_1
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - s3transfer=0.6.0=pyhd8ed1ab_0
  - scikit-learn=1.2.0=py39h57c6424_0
  - scipy=1.9.3=py39h18313fe_2
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.6.3=pyhd8ed1ab_0
  - shapely=1.8.4=py39ha5c1773_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - stable-baselines3=1.5.0=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - svt-av1=1.4.1=h7ea286d_0
  - sympy=1.11.1=py39h2804cbe_2
  - tensorboard=2.11.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py39he2a39a8_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - torchvision=0.15.0.dev20221223=py39_cpu
  - tornado=6.2=py39h02fc5c5_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.8.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - unicodedata2=15.0.0=py39h02fc5c5_0
  - urllib3=1.26.13=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.2=pyhd8ed1ab_0
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - widgetsnbextension=4.0.4=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.8.2=py39h02fc5c5_0
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.11.0=pyhd8ed1ab_0
  - zlib=1.2.13=h03a7124_4
  - zstd=1.5.2=h8128057_4
  - pip:
      - argparse==1.4.0
      - bayesian-optimization==1.4.2
      - cloudpickle==2.2.0
      - deepdiff==6.2.3
      - et-xmlfile==1.1.0
      - ffmpeg-python==0.2.0
      - future==0.18.2
      - gym-notices==0.0.8
      - gym-ple==0.3
      - igraph==0.10.3
      - jsonpickle==3.0.1
      - kaggle==1.5.12
      - llvmlite==0.39.1
      - networkx==3.0
      - numba==0.56.4
      - numpy==1.23.5
      - opencv-python==4.7.0.68
      - openpyxl==3.0.10
      - ordered-set==4.1.0
      - orjson==3.8.5
      - palettable==3.3.0
      - pandapower==2.11.1
      - pygame==2.1.2
      - pyglet==1.5.27
      - python-igraph==0.10.3
      - python-slugify==7.0.0
      - text-unidecode==1.3
      - texttable==1.6.7
      - vidmaker==2.3.0
      - xlsxwriter==3.0.7
prefix: /Users/blazdobravec/opt/miniconda3/envs/torch-rl
